PROJ_NAME=vga
DEBUG=yes
BENCH=no
MULDIV=no


SRCS = 	$(wildcard src/*.c) \
	    $(wildcard src/*.cpp)  \
	    $(wildcard src/*.S)
	    
	    

LDSCRIPT = ../../../resources/linker.ld
INC += -I../../../libs/

include ../../../resources/gcc.mk
include ../../../resources/subproject.mk


			
