PROJ_NAME=simple
DEBUG=no
BENCH=no
MULDIV?=yes

SRCS = 	$(wildcard src/*.c)  \
	$(wildcard src/*.S)

LDSCRIPT = ../libs/simple.ld


include ../../../resources/gcc.mk
include ../../../resources/subproject.mk


			
