PROJ_NAME=brieyUart
DEBUG=yes
BENCH=no
MULDIV=no


SRCS = 	$(wildcard src/*.c) \
	$(wildcard src/*.cpp)  \
	$(wildcard src/*.S)

LDSCRIPT = ../../resources/linker.ld


include ../../resources/gcc.mk
include ../../resources/subproject.mk


			
